### ISSUE TITLE
This works on stable!

### ISSUE THREAD

**Issue by limira** [Pauan/rust-signals#12]
Hi, just for the case you have not noticed yet. Both this and Dominator compile successfully on Rust stable (1.38).

**Comment by Pauan** [comment]
That's good news, though the really exciting part will be when 1.39 hits stable, because then we get async/await.

**Comment by kellytk** [comment]
@Pauan Re: async/await, may I ask your thoughts on the road ahead now that 1.39 has been released?

**Comment by Pauan** [comment]
@kellytk There isn't really much for futures-signals to do, the API is solid and very stable (though I wouldn't mind adding a few more combinators).

We've had `async`/`await` support since [October 2018](https://github.com/Pauan/rust-signals/commit/a15860c48e18b7ec107a426a8022c0c3b0bddcce), so I don't need to do anything with regards to that, everything should already work.

I can't release `1.0` until after `futures` itself is `1.0`, so at this point it's just a matter of polish and docs.

**Comment by Pauan** [comment]
`async`/`await` has been on stable for a while now, and I tested to verify that `futures-signals` works on stable.

It will be a while before `futures` is `1.0`, so I'm going to close this.
